In [1]:
import pandas as pd
import numpy as np

In [46]:
data1 = pd.read_csv('application_data.csv')
data2 = pd.read_csv('previous_application.csv')

In [3]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25233 entries, 0 to 25232
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(103), int64(3), object(16)
memory usage: 23.5+ MB

In [4]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46986 entries, 0 to 46985
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SK_ID_PREV                   46986 non-null  int64
 1   SK_ID_CURR                   46986 non-null  int64
 2   NAME_CONTRACT_TYPE           46986 non-null  object
 3   AMT_ANNUITY                  36985 non-null  float64
 4   AMT_APPLICATION              46986 non-null  float64
 5   AMT_CREDIT                   46986 non-null  float64
 6   AMT_DOWN_PAYMENT             23126 non-null  float64
 7   AMT_GOODS_PRICE              36850 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   46986 non-null  object
 9   HOUR_APPR_PROCESS_START      46986 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  46986 non-null  object
 11  NFLAG_LAST_APPL_IN_DAY       46986 non-null  int64
 12  RATE_DOWN_PAYMENT            23126 non-null  float64
 13  RATE_INTEREST_PRIMARY        153 non-null    float64
 14  RATE_INTEREST_PRIVILEGED     153 non-null    float64
 15  NAME_CASH_LOAN_PURPOSE       46986 non-null  object
 16  NAME_CONTRACT_STATUS         46985 non-null  object
 17  DAYS_DECISION                46985 non-null  float64
 18  NAME_PAYMENT_TYPE            46985 non-null  object
 19  CODE_REJECT_REASON           46985 non-null  object
 20  NAME_TYPE_SUITE              24167 non-null  object
 21  NAME_CLIENT_TYPE             46985 non-null  object
 22  NAME_GOODS_CATEGORY          46985 non-null  object
 23  NAME_PORTFOLIO               46985 non-null  object
 24  NAME_PRODUCT_TYPE            46985 non-null  object
 25  CHANNEL_TYPE                 46985 non-null  object
 26  SELLERPLACE_AREA             46985 non-null  float64
 27  NAME_SELLER_INDUSTRY         46985 non-null  object
 28  CNT_PAYMENT                  36984 non-null  float64
 29  NAME_YIELD_GROUP             46985 non-null  object
 30  PRODUCT_COMBINATION          46977 non-null  object
 31  DAYS_FIRST_DRAWING           28881 non-null  float64
 32  DAYS_FIRST_DUE               28881 non-null  float64
 33  DAYS_LAST_DUE_1ST_VERSION    28881 non-null  float64
 34  DAYS_LAST_DUE                28881 non-null  float64
 35  DAYS_TERMINATION             28881 non-null  float64
 36  NFLAG_INSURED_ON_APPROVAL    28881 non-null  float64
dtypes: float64(17), int64(4), object(16)
memory usage: 13.3+ MB

In [5]:
# Identify numerical and categorical columns
num_cols = data1.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = data1.select_dtypes(include=['object']).columns.tolist()

print("Numeric columns:", len(num_cols))
print("Categorical columns:", len(cat_cols))

Numeric columns: 106
Categorical columns: 16

In [6]:
num_cols_2 = data2.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols_2 = data2.select_dtypes(include=['object']).columns.tolist()

print("Numeric columns in previous_application:", len(num_cols_2))
print("Categorical columns in previous_application:", len(cat_cols_2))

Numeric columns in previous_application: 21
Categorical columns in previous_application: 16

In [7]:
days_cols = [col for col in data1.columns if 'DAYS' in col]
for col in days_cols:
    data1[col] = pd.to_numeric(data1[col], errors='coerce').abs()

In [8]:
data1.loc[data1['DAYS_EMPLOYED'] == 365243, 'DAYS_EMPLOYED'] = np.nan

In [9]:
for col in cat_cols:
    data1[col] = data1[col].astype('string')

In [10]:
for col in cat_cols_2:
    data2[col] = data2[col].astype('string')

In [11]:
for col in num_cols:
    mean_value = data1[col].mean()
    data1.loc[:, col] = data1[col].fillna(mean_value)

In [12]:
for col in cat_cols:
    data1.loc[:, col] = data1[col].fillna("Unknown")

In [13]:
# Numerical
for col in num_cols_2:
    mean_value = data2[col].mean()
    data2.loc[:, col] = data2[col].fillna(mean_value)

# Categorical
for col in cat_cols_2:
    data2.loc[:, col] = data2[col].fillna("Unknown")

In [14]:
data1.isnull().sum().sum()

np.int64(0)

In [15]:
data2.isnull().sum().sum()

np.int64(0)

In [16]:
data1.info()
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25233 entries, 0 to 25232
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(103), int64(3), string(16)
memory usage: 23.5 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46986 entries, 0 to 46985
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SK_ID_PREV                   46986 non-null  int64
 1   SK_ID_CURR                   46986 non-null  int64
 2   NAME_CONTRACT_TYPE           46986 non-null  string
 3   AMT_ANNUITY                  46986 non-null  float64
 4   AMT_APPLICATION              46986 non-null  float64
 5   AMT_CREDIT                   46986 non-null  float64
 6   AMT_DOWN_PAYMENT             46986 non-null  float64
 7   AMT_GOODS_PRICE              46986 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   46986 non-null  string
 9   HOUR_APPR_PROCESS_START      46986 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  46986 non-null  string
 11  NFLAG_LAST_APPL_IN_DAY       46986 non-null  int64
 12  RATE_DOWN_PAYMENT            46986 non-null  float64
 13  RATE_INTEREST_PRIMARY        46986 non-null  float64
 14  RATE_INTEREST_PRIVILEGED     46986 non-null  float64
 15  NAME_CASH_LOAN_PURPOSE       46986 non-null  string
 16  NAME_CONTRACT_STATUS         46986 non-null  string
 17  DAYS_DECISION                46986 non-null  float64
 18  NAME_PAYMENT_TYPE            46986 non-null  string
 19  CODE_REJECT_REASON           46986 non-null  string
 20  NAME_TYPE_SUITE              46986 non-null  string
 21  NAME_CLIENT_TYPE             46986 non-null  string
 22  NAME_GOODS_CATEGORY          46986 non-null  string
 23  NAME_PORTFOLIO               46986 non-null  string
 24  NAME_PRODUCT_TYPE            46986 non-null  string
 25  CHANNEL_TYPE                 46986 non-null  string
 26  SELLERPLACE_AREA             46986 non-null  float64
 27  NAME_SELLER_INDUSTRY         46986 non-null  string
 28  CNT_PAYMENT                  46986 non-null  float64
 29  NAME_YIELD_GROUP             46986 non-null  string
 30  PRODUCT_COMBINATION          46986 non-null  string
 31  DAYS_FIRST_DRAWING           46986 non-null  float64
 32  DAYS_FIRST_DUE               46986 non-null  float64
 33  DAYS_LAST_DUE_1ST_VERSION    46986 non-null  float64
 34  DAYS_LAST_DUE                46986 non-null  float64
 35  DAYS_TERMINATION             46986 non-null  float64
 36  NFLAG_INSURED_ON_APPROVAL    46986 non-null  float64
dtypes: float64(17), int64(4), string(16)
memory usage: 13.3 MB

In [17]:
data1['AGE_YEARS'] = data1['DAYS_BIRTH'] / 365

In [18]:
data1['YEARS_EMPLOYED'] = data1['DAYS_EMPLOYED'] / 365

In [19]:
data1['CREDIT_INCOME_RATIO'] = data1['AMT_CREDIT'] / data1['AMT_INCOME_TOTAL']

In [20]:
data1['ANNUITY_INCOME_RATIO'] = data1['AMT_ANNUITY'] / data1['AMT_INCOME_TOTAL']

In [21]:
data1['AMT_INCOME_TOTAL'].describe()
data1['AMT_CREDIT'].describe()
data1['DAYS_EMPLOYED'].describe()
data1['AGE_YEARS'].describe()

count    25233.000000
mean        43.886971
std         11.935498
min         21.041096
25%         33.879452
50%         43.101370
75%         53.852055
max         68.991781
Name: AGE_YEARS, dtype: float64

In [22]:
for col in data1.select_dtypes(include='string').columns:
    print(col, data1[col].nunique())

NAME_CONTRACT_TYPE 2
CODE_GENDER 2
FLAG_OWN_CAR 2
FLAG_OWN_REALTY 2
NAME_TYPE_SUITE 8
NAME_INCOME_TYPE 6
NAME_EDUCATION_TYPE 6
NAME_FAMILY_STATUS 6
NAME_HOUSING_TYPE 7
OCCUPATION_TYPE 19
WEEKDAY_APPR_PROCESS_START 8
ORGANIZATION_TYPE 59
FONDKAPREMONT_MODE 5
HOUSETYPE_MODE 4
WALLSMATERIAL_MODE 8
EMERGENCYSTATE_MODE 3

In [23]:
data1

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AGE_YEARS,YEARS_EMPLOYED,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,25.920548,1.745205,2.007889,0.121978
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45.931507,3.254795,4.790750,0.132217
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.180822,0.616438,2.000000,0.100000
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.007186,0.007461,0.033138,0.270414,0.263731,1.890471,52.068493,8.326027,2.316167,0.219900
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,54.608219,8.323288,4.222222,0.179963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25228,129344,0,Cash loans,F,N,Y,0,157500.0,868500.0,25524.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,49.964384,20.254795,5.514286,0.162057
25229,129346,0,Cash loans,F,N,N,0,67500.0,61263.0,4576.5,...,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,55.424658,6.573697,0.907600,0.067800
25230,129347,0,Cash loans,F,N,Y,0,157500.0,900000.0,29164.5,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,58.830137,0.575342,5.714286,0.185171
25231,129348,0,Revolving loans,M,N,Y,1,270000.0,270000.0,13500.0,...,0.000000,0.000000,0.000000,2.000000,0.000000,2.000000,42.558904,4.536986,1.000000,0.050000
25232,129350,0,Cash loans,F,N,Y,3,90000.0,923454.0,29920.5,...,0.007186,0.007461,0.033138,0.270414,0.263731,1.890471,43.886971,6.573697,10.260600,0.332450

In [ ]:
data2

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430000,17145.0,17145.0,0.000000,17145.000000,SATURDAY,15,...,Connectivity,12.00000,middle,POS mobile with interest,365243.00000,-42.000000,300.000000,-42.000000,-37.000000,0.000000
1,2802425,108129,Cash loans,25188.615000,607500.0,679671.0,6699.780345,607500.000000,THURSDAY,11,...,XNA,36.00000,low_action,Cash X-Sell: low,365243.00000,-134.000000,916.000000,365243.000000,365243.000000,1.000000
2,2523466,122040,Cash loans,15060.735000,112500.0,136444.5,6699.780345,112500.000000,TUESDAY,11,...,XNA,12.00000,high,Cash X-Sell: high,365243.00000,-271.000000,59.000000,365243.000000,365243.000000,1.000000
3,2819243,176158,Cash loans,47041.335000,450000.0,470790.0,6699.780345,450000.000000,MONDAY,7,...,XNA,12.00000,middle,Cash X-Sell: middle,365243.00000,-482.000000,-152.000000,-182.000000,-177.000000,1.000000
4,1784265,202054,Cash loans,31924.395000,337500.0,404055.0,6699.780345,337500.000000,THURSDAY,9,...,XNA,24.00000,high,Cash Street: high,342379.55914,13792.054223,33565.493737,76466.403838,81872.192106,0.331398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954813,1195811,110979,Cash loans,15893.795462,0.0,0.0,6699.780345,226414.899382,WEDNESDAY,13,...,XNA,15.99836,XNA,Cash,342379.55914,13792.054223,33565.493737,76466.403838,81872.192106,0.331398
954814,1366028,274265,Cash loans,15893.795462,0.0,0.0,6699.780345,226414.899382,WEDNESDAY,8,...,XNA,15.99836,XNA,Cash,342379.55914,13792.054223,33565.493737,76466.403838,81872.192106,0.331398
954815,2509864,433033,Cash loans,19493.550000,315000.0,349096.5,6699.780345,315000.000000,THURSDAY,9,...,XNA,24.00000,low_normal,Cash X-Sell: low,365243.00000,-808.000000,-118.000000,-508.000000,-492.000000,1.000000
954816,1652965,371484,Consumer loans,15649.110000,169609.5,152644.5,16965.000000,169609.500000,SATURDAY,18,...,Furniture,12.00000,middle,POS industry with interest,365243.00000,-400.000000,-70.000000,-250.000000,-243.000000,0.000000
954817,2231371,217117,Consumer loans,5909.265000,67365.0,67365.0,0.000000,67365.000000,THURSDAY,19,...,Unknown,15.99836,Unknown,Unknown,342379.55914,13792.054223,33565.493737,76466.403838,81872.192106,0.331398

In [48]:
important_cols = [
    "SK_ID_CURR",
    "TARGET",
    "NAME_CONTRACT_TYPE",
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "CNT_CHILDREN",
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "NAME_INCOME_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_TYPE_SUITE",
    "WEEKDAY_APPR_PROCESS_START",
    "OCCUPATION_TYPE",
    "ORGANIZATION_TYPE",
    "LANDAREA_AVG",
    "FLAG_PHONE",
    "FLAG_EMAIL",
    "FLAG_CONT_MOBILE",
    "FLAG_WORK_PHONE",
    "FLAG_EMP_PHONE",
    "FLAG_MOBIL"
]

In [49]:
application_data_imp = data1[important_cols].copy()

In [50]:
application_data_imp = application_data_imp.dropna()

In [51]:
print("Rows after dropping missing:", application_data_imp.shape)

Rows after dropping missing: (85475, 24)

In [27]:
def remove_outliers(df, cols):
    df_clean = df.copy()
    for col in cols:
        if df_clean[col].dtype in ['float64', 'int64', 'float32']:
            Q1 = df_clean[col].quantile(0.25)
            Q3 = df_clean[col].quantile(0.75)
            IQR = Q3 - Q1
            lower = Q1 - 1.5 * IQR
            upper = Q3 + 1.5 * IQR
            df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]
    return df_clean

In [52]:
important_cols_prev = [
    "SK_ID_PREV",
    "SK_ID_CURR",
    "NAME_CONTRACT_TYPE",
    "NAME_CONTRACT_STATUS",
    "CODE_REJECT_REASON",
    "NAME_PAYMENT_TYPE",
    "AMT_APPLICATION",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_DOWN_PAYMENT",
    "AMT_GOODS_PRICE",
    "CNT_PAYMENT",
    "NAME_CASH_LOAN_PURPOSE",
    "NAME_GOODS_CATEGORY",
    "NAME_PORTFOLIO",
    "NAME_PRODUCT_TYPE",
    "NAME_CLIENT_TYPE",
    "CHANNEL_TYPE",
    "NAME_SELLER_INDUSTRY",
    "FLAG_LAST_APPL_PER_CONTRACT",
    "NFLAG_LAST_APPL_IN_DAY",
    "NFLAG_INSURED_ON_APPROVAL",
    "DAYS_DECISION",
    "DAYS_FIRST_DRAWING",
    "DAYS_FIRST_DUE",
    "DAYS_LAST_DUE_1ST_VERSION",
    "DAYS_LAST_DUE",
    "DAYS_TERMINATION",
    "RATE_DOWN_PAYMENT",
    "RATE_INTEREST_PRIMARY",
    "RATE_INTEREST_PRIVILEGED",
    "NAME_YIELD_GROUP"
]

In [53]:
previous_application_imp = data2[important_cols_prev].copy()

In [28]:
data1_no_outliers = remove_outliers(data1, important_num_cols)

In [57]:
previous_application_imp = data2[important_cols_prev].copy()

# Fill missing numbers with mean
for col in previous_application_imp.select_dtypes(include=[np.number]).columns:
    previous_application_imp[col] = previous_application_imp[col].fillna(previous_application_imp[col].mean())

# Fill missing categorical with Unknown
for col in previous_application_imp.select_dtypes(include=['object', 'string']).columns:
    previous_application_imp[col] = previous_application_imp[col].fillna("Unknown")

In [58]:
previous_application_imp.info()
previous_application_imp.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670214 entries, 0 to 1670213
Data columns (total 32 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1670214 non-null  int64
 1   SK_ID_CURR                   1670214 non-null  int64
 2   NAME_CONTRACT_TYPE           1670214 non-null  object
 3   NAME_CONTRACT_STATUS         1670214 non-null  object
 4   CODE_REJECT_REASON           1670214 non-null  object
 5   NAME_PAYMENT_TYPE            1670214 non-null  object
 6   AMT_APPLICATION              1670214 non-null  float64
 7   AMT_CREDIT                   1670214 non-null  float64
 8   AMT_ANNUITY                  1670214 non-null  float64
 9   AMT_DOWN_PAYMENT             1670214 non-null  float64
 10  AMT_GOODS_PRICE              1670214 non-null  float64
 11  CNT_PAYMENT                  1670214 non-null  float64
 12  NAME_CASH_LOAN_PURPOSE       1670214 non-null  object
 13  NAME_GOODS_CATEGORY          1670214 non-null  object
 14  NAME_PORTFOLIO               1670214 non-null  object
 15  NAME_PRODUCT_TYPE            1670214 non-null  object
 16  NAME_CLIENT_TYPE             1670214 non-null  object
 17  CHANNEL_TYPE                 1670214 non-null  object
 18  NAME_SELLER_INDUSTRY         1670214 non-null  object
 19  FLAG_LAST_APPL_PER_CONTRACT  1670214 non-null  object
 20  NFLAG_LAST_APPL_IN_DAY       1670214 non-null  int64
 21  NFLAG_INSURED_ON_APPROVAL    1670214 non-null  float64
 22  DAYS_DECISION                1670214 non-null  int64
 23  DAYS_FIRST_DRAWING           1670214 non-null  float64
 24  DAYS_FIRST_DUE               1670214 non-null  float64
 25  DAYS_LAST_DUE_1ST_VERSION    1670214 non-null  float64
 26  DAYS_LAST_DUE                1670214 non-null  float64
 27  DAYS_TERMINATION             1670214 non-null  float64
 28  RATE_DOWN_PAYMENT            1670214 non-null  float64
 29  RATE_INTEREST_PRIMARY        1670214 non-null  float64
 30  RATE_INTEREST_PRIVILEGED     1670214 non-null  float64
 31  NAME_YIELD_GROUP             1670214 non-null  object
dtypes: float64(15), int64(4), object(13)
memory usage: 407.8+ MB

SK_ID_PREV                     0
SK_ID_CURR                     0
NAME_CONTRACT_TYPE             0
NAME_CONTRACT_STATUS           0
CODE_REJECT_REASON             0
NAME_PAYMENT_TYPE              0
AMT_APPLICATION                0
AMT_CREDIT                     0
AMT_ANNUITY                    0
AMT_DOWN_PAYMENT               0
AMT_GOODS_PRICE                0
CNT_PAYMENT                    0
NAME_CASH_LOAN_PURPOSE         0
NAME_GOODS_CATEGORY            0
NAME_PORTFOLIO                 0
NAME_PRODUCT_TYPE              0
NAME_CLIENT_TYPE               0
CHANNEL_TYPE                   0
NAME_SELLER_INDUSTRY           0
FLAG_LAST_APPL_PER_CONTRACT    0
NFLAG_LAST_APPL_IN_DAY         0
NFLAG_INSURED_ON_APPROVAL      0
DAYS_DECISION                  0
DAYS_FIRST_DRAWING             0
DAYS_FIRST_DUE                 0
DAYS_LAST_DUE_1ST_VERSION      0
DAYS_LAST_DUE                  0
DAYS_TERMINATION               0
RATE_DOWN_PAYMENT              0
RATE_INTEREST_PRIMARY          0
RATE_INTEREST_PRIVILEGED       0
NAME_YIELD_GROUP               0
dtype: int64

In [59]:
application_data_imp.to_csv("application_data_imp.csv", index=False)
previous_application_imp.to_csv("previous_application_imp.csv", index=False)

In [60]:
from google.colab import files

files.download("application_data_imp.csv")
files.download("previous_application_imp.csv")

In [56]:
previous_application_imp.to_csv("previous_application_imp.csv", index=False)

In [61]:
merged_df = previous_application_imp.merge(
    application_data_imp,
    on="SK_ID_CURR",
    how="left"
)

In [29]:
print("Original rows:", len(data1))
print("Rows after outlier removal:", len(data1_no_outliers))

Original rows: 25233
Rows after outlier removal: 22003

In [31]:
data1 = data1_no_outliers

In [32]:
import plotly.express as px

fig = px.pie(
    data1,
    names="TARGET",
    title="Default vs Non-Default Distribution",
    hole=0.4,
    color="TARGET",
    color_discrete_sequence=["#2ecc71", "#e74c3c"]  # non-default green, default red
)
fig.show()

In [33]:
fig = px.histogram(
    data1,
    x="AGE_YEARS",
    nbins=40,
    color="TARGET",
    title="Age Distribution by Default Status",
    color_discrete_sequence=["#e74c3c", "#3498db"]
)
fig.show()

In [34]:
fig = px.histogram(
    data1,
    x="AMT_INCOME_TOTAL",
    nbins=50,
    title="Income Distribution"
)
fig.show()

In [35]:
fig = px.histogram(
    data1,
    x="AMT_CREDIT",
    nbins=50,
    title="Loan Amount (Credit) Distribution"
)
fig.show()

In [37]:
fig = px.histogram(
    data1,
    x="ANNUITY_INCOME_RATIO",
    color="TARGET",
    nbins=50,
    title="EMI-to-Income Ratio Distribution by Default"
)
fig.show()

In [38]:
fig = px.box(
    data1,
    x="TARGET",
    y="AMT_INCOME_TOTAL",
    title="Income: Default vs Non-default"
)
fig.show()

In [39]:
fig = px.violin(
    data1,
    x="TARGET",
    y="AGE_YEARS",
    box=True,
    title="Age Distribution by Default Status"
)
fig.show()

In [40]:
import plotly.graph_objects as go

df_sankey = data2.groupby(
    ["NAME_CASH_LOAN_PURPOSE", "NAME_CONTRACT_STATUS"]
).size().reset_index(name="count")

# Create node lists
sources = df_sankey["NAME_CASH_LOAN_PURPOSE"].tolist()
targets = df_sankey["NAME_CONTRACT_STATUS"].tolist()
values  = df_sankey["count"].tolist()

labels = list(set(sources + targets))
label_to_index = {label: idx for idx, label in enumerate(labels)}

source_ids = [label_to_index[s] for s in sources]
target_ids = [label_to_index[t] for t in targets]

fig = go.Figure(data=[go.Sankey(
    node=dict(label=labels),
    link=dict(
        source=source_ids,
        target=target_ids,
        value=values
    )
)])

fig.update_layout(title_text="Flow: Loan Purpose → Loan Status")
fig.show()

In [42]:
import plotly.express as px

df = data1.groupby("REGION_RATING_CLIENT")["TARGET"].mean().reset_index()

fig = px.treemap(
    df,
    path=["REGION_RATING_CLIENT"],
    values="TARGET",
    color="TARGET",
    color_continuous_scale="RdYlGn_r",
    title="Default Rate by Region Rating (Symbolic Map)"
)

fig.show()

In [43]:
df = data1.groupby("REGION_POPULATION_RELATIVE")["TARGET"].mean().reset_index()

fig = px.scatter(
    df,
    x="REGION_POPULATION_RELATIVE",
    y="TARGET",
    size="REGION_POPULATION_RELATIVE",
    title="Default Rate vs Region Population Density"
)

fig.show()